# Generated by Django 5.0.1 on 2024-01-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.FilePathField(path='/projects/img'),
        ),
    ]
